version: "3.3"
services:
  db:
    image: postgres:15
    volumes:
      - data-volume:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  app:
    build: .
    restart: always
    env_file:
      - .env
    container_name: vehicle_app
    command: sh /vehicle_app/docker/app.sh
    ports:
      - "8000:8000"
    depends_on:
      - db


volumes:
  data-volume: