# Generated by Django 4.2.1 on 2023-05-25 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0003_alter_location_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator(message='Допускаются только буквы и цифры', regex='^[1-9]\\d{3}[A-Z]$')]),
        ),
    ]
